PARU_PACKAGE := terminator-git jumpapp quicktile
PARU_PACKAGE += php composer github-cli
PARU_PACKAGE += visual-studio-code-bin
PARU_PACKAGE += zoom slack-desktop postman-bin
PARU_PACKAGE += ngrok google-chrome
 
paru:
	paru -Sy ${PARU_PACKAGE}
